### ISSUE TITLE
(Feature request) an 'open' command to open our stars.

### ISSUE THREAD

**Issue by 5c0tt-b0t** [wolfg1969/oh-my-stars#16]
First thank you!!! This is great! I have so many stars and this makes searching them easy :)
Please add an 'open' command, it can use 'xdg-open' to open the star's link in our default browser.
Then it is PERFECT.
Thank you again!

**Comment by seanbreckenridge** [comment]
Is a feature I wanted as well, so [ended up forking this](https://github.com/seanbreckenridge/oh-my-stars) to more fit my needs.

As a workaround, one can use [`urlextract`](https://pypi.org/project/urlextract/) against the output of this, like:

`mystars 'search query' | urlextract | head -n 1 | xargs python3 -m webbrowser`

Instead of just picking the first result, one could use [`fzf`](https://github.com/junegunn/fzf) to pick one:

```bash
#!/bin/sh
mystars "$@" | urlextract | fzf | xargs python3 -m webbrowser
```

The `webbrowser` module should handle opening on all platforms, else replace with a `xdg-open`/direct call to firefox/chrome from the command line.

**Comment by 5c0tt-b0t** [comment]
I'll close this as its stale. I use the above fork.
